FROM centos:7

MAINTAINER Bumjoon Kim <nunojun@gmail.com>

RUN yum update -y
RUN curl -jksSLH "Cookie: oraclelicense=accept-securebackup-cookie" \
    http://download.oracle.com/otn-pub/java/jdk/9.0.4+11/c2514751926b4512b076cc82f959763f/jre-9.0.4_linux-x64_bin.rpm \
    -o jre.rpm
RUN yum localinstall -y jre.rpm
RUN rm -f jre.rpm
