FROM centos:7

MAINTAINER Bumjoon Kim <nunojun@gmail.com>

RUN yum update -y
RUN curl -jksSLH "Cookie: oraclelicense=accept-securebackup-cookie" \
    http://download.oracle.com/otn-pub/java/jdk/8u161-b12/2f38c3b165be4555a1fa6e98c45e0808/jre-8u161-linux-x64.rpm \
    -o jre.rpm
RUN yum localinstall -y jre.rpm
RUN rm -f jre.rpm
